# Generated by Django 6.0.2 on 2026-02-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_cancelled_at_booking_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
    ]
