# Generated by Django 6.0.2 on 2026-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва')),
                ('capacity', models.PositiveIntegerField(verbose_name='Кількість місць')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Проектор')),
                ('has_speakerphone', models.BooleanField(default=False, verbose_name='Спікерфон')),
                ('has_tv', models.BooleanField(default=False, verbose_name='Телевізор / екран')),
                ('has_whiteboard', models.BooleanField(default=False, verbose_name='Маркерна дошка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Переговорна кімната',
                'verbose_name_plural': 'Переговорні кімнати',
                'ordering': ['name'],
            },
        ),
    ]
