# Generated by Django 6.0.2 on 2026-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Очікує підтвердження'), ('APPROVED', 'Підтверджено'), ('REJECTED', 'Відхилено'), ('CANCELLED', 'Скасовано')], default='PENDING', max_length=20),
        ),
    ]
